//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace C1ASPRMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int Id { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public string sq { get; set; }
        public string sa { get; set; }
        public string fn { get; set; }
        public string mn { get; set; }
        public string ln { get; set; }
        public string gender { get; set; }
        public string ms { get; set; }
        public string dob { get; set; }
        public string occ { get; set; }
        public int mob { get; set; }
        public string email { get; set; }
        public string nationality { get; set; }
        public string country { get; set; }
        public string address { get; set; }
        public string state { get; set; }
        public string pin { get; set; }
    }
}
